language:
  - c
install:
  - sudo apt-get update
  - sudo apt-get install linuxdoc-tools linuxdoc-tools-info binutils-mingw-w64-i686 gcc-mingw-w64-i686 sshpass
  before_script:
  - git checkout https://github.com/vm6502q/qrack.git qrack
script:
  - ENABLE_OPENCL=0 make
